### YamlMime:ManagedReference
items:
- uid: MovieAppApi.Src.Core.Services.Environment
  commentId: N:MovieAppApi.Src.Core.Services.Environment
  id: MovieAppApi.Src.Core.Services.Environment
  children:
  - MovieAppApi.Src.Core.Services.Environment.EnvService
  - MovieAppApi.Src.Core.Services.Environment.IEnvService
  langs:
  - csharp
  - vb
  name: MovieAppApi.Src.Core.Services.Environment
  nameWithType: MovieAppApi.Src.Core.Services.Environment
  fullName: MovieAppApi.Src.Core.Services.Environment
  type: Namespace
  assemblies:
  - MovieAppApi
references:
- uid: MovieAppApi.Src.Core.Services.Environment.EnvService
  commentId: T:MovieAppApi.Src.Core.Services.Environment.EnvService
  href: MovieAppApi.Src.Core.Services.Environment.EnvService.html
  name: EnvService
  nameWithType: EnvService
  fullName: MovieAppApi.Src.Core.Services.Environment.EnvService
- uid: MovieAppApi.Src.Core.Services.Environment.IEnvService
  commentId: T:MovieAppApi.Src.Core.Services.Environment.IEnvService
  parent: MovieAppApi.Src.Core.Services.Environment
  href: MovieAppApi.Src.Core.Services.Environment.IEnvService.html
  name: IEnvService
  nameWithType: IEnvService
  fullName: MovieAppApi.Src.Core.Services.Environment.IEnvService
- uid: MovieAppApi.Src.Core.Services.Environment
  commentId: N:MovieAppApi.Src.Core.Services.Environment
  href: MovieAppApi.html
  name: MovieAppApi.Src.Core.Services.Environment
  nameWithType: MovieAppApi.Src.Core.Services.Environment
  fullName: MovieAppApi.Src.Core.Services.Environment
  spec.csharp:
  - uid: MovieAppApi
    name: MovieAppApi
    href: MovieAppApi.html
  - name: .
  - uid: MovieAppApi.Src
    name: Src
    href: MovieAppApi.Src.html
  - name: .
  - uid: MovieAppApi.Src.Core
    name: Core
    href: MovieAppApi.Src.Core.html
  - name: .
  - uid: MovieAppApi.Src.Core.Services
    name: Services
    href: MovieAppApi.Src.Core.Services.html
  - name: .
  - uid: MovieAppApi.Src.Core.Services.Environment
    name: Environment
    href: MovieAppApi.Src.Core.Services.Environment.html
  spec.vb:
  - uid: MovieAppApi
    name: MovieAppApi
    href: MovieAppApi.html
  - name: .
  - uid: MovieAppApi.Src
    name: Src
    href: MovieAppApi.Src.html
  - name: .
  - uid: MovieAppApi.Src.Core
    name: Core
    href: MovieAppApi.Src.Core.html
  - name: .
  - uid: MovieAppApi.Src.Core.Services
    name: Services
    href: MovieAppApi.Src.Core.Services.html
  - name: .
  - uid: MovieAppApi.Src.Core.Services.Environment
    name: Environment
    href: MovieAppApi.Src.Core.Services.Environment.html
